### ISSUE TITLE
Single solution?

### ISSUE THREAD

**Issue by hakank** [corail-research/SeaPearlZoo#11]
I've tested SeaPearl.jl /  SeaPearlZoo a little and noticed that the examples (e.g.  n_queens, All-interval_Series) search for all solutions, but for even quite small sizes this takes long time (e.g. 20 queens) . How would I change e.g. n_queens to just get just a single solution, or in general k solutions?

**Comment by 3rdCore** [comment]
Actually, you can set the limit of solution to search during the initialization of the CP model. This parameter is `model.limit.numberOfSolutions`. Thinks become tricky when you have to manually change this parameter in the n-queens generator In SeaPearl. As for now, `train()` function doesn't provide this control.

**Comment by hakank** [comment]
Thanks for you answer. Now it's manageable to solve 100 queens (about 10s) by changing in classic_cp/n_queens/n_queens.jl (by adding `model.limit.numberOfSolutions = 1` in the model_queens(Int) method).

However, this is the classic_cp example, but it's probably more interesting to test the learning_cp examples.
