### ISSUE TITLE
Fix/improve the coloring problem in classic_cp 

### ISSUE THREAD

**Issue by marco-novaes98** [corail-research/SeaPearlZoo#19]
Update Readme (ex: explain the format of instances …)
Add headers and comments 
In “Breaking some symmetries”, is the 2nd constraint useful? Can we add another constraint to break symmetries?
Use addConstraint! instead of pushing constraints to the model
Add @time to solve!()
Filter solutions to only print optimal solution
Fix outputFromSeaPearl (optimality always false, edgeColors is wrong …)
What's the purpose of testGraph(), should we remove it?
Ensure that all TODO comments are managed

**Comment by jardinetsouffleton** [comment]
This is no longer an issue.
